pluginManagement {
	repositories {
		maven {
			url = "https://maven.wagyourtail.xyz/releases"
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe Releases'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe Snapshots'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = rootProject.projectDir.getName()